### ISSUE TITLE
Confusion with two different Properties drop-downs

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/json-schema-editor#11]
There is some UI confusion over the two `Properties` buttons:
![image](https://user-images.githubusercontent.com/1108513/53486632-23f59500-3a81-11e9-9d07-ddbc30e24f66.png)

The first refers to the visibility of the fixed set of attributes available when describing a schema object.

The second refers to a customisable set of properties that we're adding to this element.

The second one is already within a "Properties" area, so I guess we could rename it do add/remove.

**Comment by IanMayo** [comment]
Hmm, I've had a look at the HTML:
![image](https://user-images.githubusercontent.com/1108513/53486932-0412a100-3a82-11e9-90bf-ece56c29e780.png)

Both buttons are type `json-editor-btntype-properties`.  The first is within data-schemapath of "root", the second is within data-schemapath "root.properties".

So, if we modified the button type depending on if the data-schemapath ended in`.properties` or not, we could modify the appearance, I guess.

**Comment by IanMayo** [comment]
@pmk65 - from your familiarity with the codebase, are you able to offer any tips on how we could separate these two different types of `Property` drop-down list?

**Comment by pmk65** [comment]
The "Properties" button/modal is generated every time you have an object in your schema. (src/editors/object.js, inside the `build()` function, line 730)
The button class name was something I added a while ago, so you could style the individual button types through CSS.

The "root" name is just a default value, it is possible to override it if you set the "id"
Wrapper DIV with no ID set:
`<div data-schemaid="root" data-schematype="object" data-schemapath="root" style="position: relative;">`
Wrapped DIV with ID set to "myCustomId":
`<div data-schemaid="myCustomId" data-schematype="object" data-schemapath="root" style="position: relative;">`

It looks like the `data-schemapath` keeps the `root` value. So it should be possible to add a check for "root" and then modify the button. But it's something you need to post on the JSON-Editor issue tracker, as I don't know if it would have any unforeseen issues. And there might be others who know more.

A "dirty" approach would be to add a small JavaScript function that runs when the form is generated/ready. This won't require any modifications to the JSON-Editor library and you have full control of what to change.

````javascript
jseditor.on('ready', function() {
  var rootPropButton = document.querySelector('div[data-schemapath="root"] button.json-editor-btntype-properties');
  if (rootPropButton) {
    var propButtonTitle = rootPropButton.querySelector('span');
    propButtonTitle.innerText = 'Master Properties';
  }
});
````

Live Example: https://is.gd/OcA9q1

**Comment by IanMayo** [comment]
@Franciman - I'd like us to have a go at the small Javascript function strategy, please.

**Comment by Franciman** [comment]
@pmk65 we would also like to also change the icon of the button, is it possible to do it?
In particular, instead of a pen we'd like to use a gear for the root "Properties" button.
Thanks in advance.

**Comment by pmk65** [comment]
Sure. The icon is an "i" tag with classnames to control the glyph. 
````html
<i class="glyphicon glyphicon-pencil"></i>
````
To access it, you just add this to the example I made previously.
````javascript
var propButtonIcon = rootPropButton.querySelector('i');
propButtonIcon.classList.remove('glyphicon-pencil')
propButtonIcon.classList.add(' glyphicon-your-icon-def');
````
The class names might differ depending on which theme is used.

**Comment by Franciman** [comment]
Thanks @pmk65. What if I want to change the icon for all properties buttons? I need to hook on 'change' instead of 'ready' and use `querySelectorAll` ? Or is there another way?

**Comment by pmk65** [comment]
You could also setup a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) and watch for occurrence of the Properties button. Using this method you only need to set it up once and don't have to worry about changes.

**Comment by IanMayo** [comment]
@Franciman  -  I expect you're aware of this already, but the `Production` example still uses `Properties` for both drop-downs.

**Comment by Franciman** [comment]
Yes, I haven't integrated the solution yet, because I used a different approach and now I am trying what @pmk65 suggested

**Comment by pmk65** [comment]
@Franciman I made an example using Mutation Observers, but there's some problems.
JSON-Editor apparently create some DOM elements and then removes them again which causes the Mutation Observer to trigger for elements which is not present in the displayed form.

You can see an example here: https://is.gd/Z6BzIt
I just created a simple counter and added the value to the Properties button text.
Notice that there's no 1 and 2 (Those have been removed before displaying)

Update: Looks like the removed buttons triggering it is because I destroyed and regenerated the form. So it is working correctly. See: https://is.gd/fWKkH8

**Comment by Franciman** [comment]
Thank you very much for your help @pmk65 
Here is what I came up with:

```javascript
    // Check whether the node is a properties button for an object,
    // and not for the schema of an object named properties
    var isObjectPropertiesButton = function(node) {
        // Does the path end in '.properties'?
        if(node.matches('div[data-schemapath$=".properties"] > h3 > div > button.json-editor-btntype-properties')) { 
            var containingDiv = node.parentElement.parentElement.parentElement;
            var span = containingDiv.querySelector('h3 > span');

            // Is it an object properties or a property named properties?
            if(span && span.innerText === 'properties') { 
                return true;
            }
        }
        return false;
    };

    this.observer = new MutationObserver(function(mutationsList, observer) {
        for(var mutation of mutationsList) {
            mutation.addedNodes.forEach(function(node) {
                if(node.nodeType == 1) {
                    if(isObjectPropertiesButton(node)) {
                        node.querySelector('span').innerText = 'Add/Remove';
                    }
                    else if(node.matches('button.json-editor-btntype-properties')) {
                        // For other properties buttons, remove the 'Properties' label,
                        // and use a cog as icon
                        var icon = node.querySelector('i');
                        icon.classList.remove('fa-pencil');
                        icon.classList.add('fa-cog');

                        var span = node.querySelector('span');
                        span.innerText = '';
                    }
                }
            });
        }
    });

    this.observer.observe(this.renderZone, { childList: true, subtree: true });

```

It only goes over added nodes, and it doesn't visit two times the same node (not sure if it is correct, though, I could use some advice from you).

I have some questions for you:
In your example what does this line do:
>   MutationObserver = win.MutationObserver || win.WebKitMutationObserver,
  observer;

Also, I tried changing icons as you suggested: 

```javascript
var icon = node.querySelector('i');
                        icon.classList.remove('fa-pencil');
                        icon.classList.add('fa-cog');
```

but it doesn't work, the pencil is kept. The code is executed, and the change is done, but it seems like there is something else the JSON Editor does that re-establishes the pencil icon.

Finally I noticed that JSON Editor has some issues if you insert property names with dots. Is it something worth opening an issue?

**Comment by pmk65** [comment]
>
> I have some questions for you:
> In your example what does this line do:
> 
> > MutationObserver = win.MutationObserver || win.WebKitMutationObserver,
> > observer;
>

It's just a fallback for old versions of Chrome that uses a custom name "WebKitMutationObserver" instead of "MutationObserver"

> Also, I tried changing icons as you suggested:
> but it doesn't work, the pencil is kept. The code is executed, and the change is done, but it seems like there is something else the JSON Editor does that re-establishes the pencil icon.

Is this code live so I can test/see the resulting HTML?
Inspecting the HTML code using the Browser Inspector functionality, should display the classes used for the icon.

> Finally I noticed that JSON Editor has some issues if you insert property names with dots. Is it something worth opening an issue?

There's already an open issue regarding the dot in names: https://github.com/json-editor/json-editor/issues/231#issuecomment-443509512

**Comment by Franciman** [comment]
Thank you!
Oh and I found out why the icons weren't working. I tried to remove 'fa-pencil', but it is 'fa-pen' class.
Here is the demo: http://franciman.github.io/

**Comment by IanMayo** [comment]
very good :-)
