### ISSUE TITLE
Need support for `range` for integer

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/json-schema-editor#14]
I've seen the `range` format, which introduces a slider.

I guess it only applies to integers.  That means that for integer we need to allow the `format` property.  We also need to allow the min/max values to be specified.

**Comment by Franciman** [comment]
There is also a `number` format, it introduces a stepper. It may be useful too for integers and numbers.

Also `range` and `number` don't seem to be really interesting for string types, can i remove them from the allowed formats for string?

**Comment by IanMayo** [comment]
sure, yes please.

**Comment by Franciman** [comment]
@pmk65 when using the `range` format, the starting value of the slider is `undefined`, so I need to specify a `default` value for the integer. Whilst for the `number` format this is not needed and it starts at 0. Is it intended?

**Comment by pmk65** [comment]
I never used ranges, so I really don't know. Try asking on the main JSON-Editor repo. BBut it sounds like a bug.
