### ISSUE TITLE
Consume all screen width in production demo

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/json-schema-editor#17]
In the `production.html` demo file we put the editor above the preview.  But, the controls only consume about 60% of the screen width.

If the controls were set to consume 100%, there would be more instances when the controls can be laid out horizontally (grid, table), reducing the height required, and making more data visible.

**Comment by pmk65** [comment]
I would recomend a max width of 1200px for the forms.

**Comment by IanMayo** [comment]
Thanks again for your support @pmk, is there a reason why a hard-coded pixel width is better than 100% ?

**Comment by pmk65** [comment]
Just readability. And the user who makes a schema/form for use on his/her own page would probably use an even smaller size.
