### ISSUE TITLE
Restrict top level types

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/json-schema-editor#4]
To make this schema editor as efficient as possible, I propose we reduce the choices when possible.

Currently the list of top-level object types is quite large:
![image](https://user-images.githubusercontent.com/1108513/53090300-e2a43900-3506-11e9-9e7b-46ebfc7f0830.png)

I propose we trim it to `object` and `array`.  (I'm almost tempted to drop the `array` type, since the object we're creating will still be some logical collection of items.  But, let's defer that).

Even if the user wants to just capture the name of a person (as a String) it would still be "good practice" to include that in a recognisable object:

````
{
  "type": "object",
  "title": "Person",
  "description":"Definition of a person",
  "properties": {
    "Name": {
      "title": "Name",
      "type": "string",
      "description": "Name of this person"
    }
  },
  "required":["Name"]
}
````
rather than:
````
{
  "title": "Name",
  "type": "string",
  "description": "Name of this person"
}
````

**Comment by IanMayo** [comment]
Oh, and @Franciman - I'm quite happy to debate the merits of this issue - if you have other ideas/opinions

**Comment by Franciman** [comment]
I think that only object for top level is enough, because the object gives you the opportunity to add some tagging data to the array so it is always preferable. And when you just need the array it's little overhead:
> [ 1, 2, 3]

Compared to:
```json
{
    "title": "My favourite numbers",
    "items": [1, 2, 3]
}
```

Or even just:
```json
{ "items": [1, 2, 3] }
```

**Comment by IanMayo** [comment]
Great - let's just go for `object` at the top level. We may then be able to remove the drop-down:
![image](https://user-images.githubusercontent.com/1108513/53095780-8ac0fe80-3515-11e9-85af-b6d997bc4492.png)
