### ISSUE TITLE
Enable git pages

### ISSUE THREAD

**Issue by pmk65** [DeepBlueCLtd/json-schema-editor#6]
Enable [Github Pages](https://pages.github.com/) so that the example can run directly off the github repo.

**Comment by IanMayo** [comment]
Good suggestion @pmk65 

I was looking for a way of doing "live preview" of branches for PRs.  But, having a preview of `master` would still be good.

**Comment by pmk65** [comment]
For previewing HTML files in branches, you can use this: https://htmlpreview.github.io/

**Comment by IanMayo** [comment]
Done - hosting here: https://deepbluecltd.github.io/json-schema-editor/
