### ISSUE TITLE
Update Preview - alternate method

### ISSUE THREAD

**Issue by pmk65** [DeepBlueCLtd/json-schema-editor#7]
I tried the direct link and it looks good. But having to click the "Update Preview" after every change really annoyed me. 😢 
I suggest you add an option so the user can choose if he/she wants to click the "Update Preview" button or have the preview auto update when you make changes in the editor.

Just add a onchange event to the editor, and then update the preview when a change occurs,.

````javascript
metaEditor.on('change',function() {
  // Update previewEditor 
});
````

**Comment by Franciman** [comment]
Oh, good. I think it makes sense to make this the default behavior
